name: CI

on: [push]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.3', '8.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: php-actions/composer@v6 # or alternative dependency management
        with:
          php_version: ${{ matrix.php-versions }}

      - name: PHPUnit tests
        uses: php-actions/phpunit@v4
        with:
          php_version: ${{ matrix.php-versions }}